name: rpi_spi
version: 0.4.0
author: Dan Rubel <danrubel@google.com>
description: rpi_spi is a Dart library for using SPI on the Raspberry Pi.
homepage: https://github.com/danrubel/rpi_spi.dart

# This package only works with Linux running on Raspberry Pi
platforms:
  linux:
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  ffi: ^2.1.2
  path: '>=1.0.0 <2.0.0'
dev_dependencies:
  grinder: ^0.9.0
  pedantic: 1.11.1
  test: ^1.17.9
